app:
  info: Kafka event publisher with pluggable components
  version: 1.0.0
http:
  port: 8080
  path:
    api: api
    ui: ui
producer:
  bootstrap_servers: [localhost:9092]
encoders:
  avro:
    schema_reg: localhost:8081
  string:
  json:
partitioners:
  static:
  murmer: