app:
  info: Kafka event publisher with pluggable components
  version: 1.0.0
http:
  port: 8080
  path:
    api: api
    ui: ui
plugins:
  dir: plugins
  encoders:
  partitioners:
producer:
  bootstrap_servers: [localhost:9092]
encoders:
  byte:
partitioners:
  defined:
  random:
    seed: 10