POST http://localhost:8080/api
Content-Type: application/json

{
  "topic": "test-topic",
  "headers": {
    "header1": "header_val1"
  },
  "key": {
    "type": "byte",
    "value": "key"
  },
  "value": {
    "type": "byte",
    "value": {
      "json_key": "value"
    }
  },
  "partitioner": {
    "type": "defined",
    "partition": "2"
  }
}

###
